### PR TITLE
Remove Twitter and comment out queries

### PR DESCRIPTION
**Pull request by attaboy**
Remove Twitter data source plugin and replace all the queries with a super basic dummy one for now to get the site working in the most barebones way.

I'm able to see the site running with these changes, albeit with no data. Should be a starting point at least!

### CODE REVIEW

**Comment by attaboy** [comment]
https://5e855c2d5eeeb800068f73a9--maskmakers.netlify.com

Don't click the left arrow button 😂 🔁💥

**Comment by attaboy** [comment]
I'm not sure if you're planning to use https://seeker.company/ still? I left the code around for it but mostly commented out.

**Review by djirdehh — APPROVED** [review]
This looks great 👍 . I've checked out from this branch to make some initial UI changes/etc.

**Review by ben-che — APPROVED** [review]
lgtm as well!

**Pull request merged**
